const id = (label) => ({ name: label, label, type: "text" });
const text = (name, label = name, required = false) => ({ name, label, required });
const num = (name, label = name) => ({ name, label, type: "number" });
const bool = (name, label = name) => ({ name, label, type: "checkbox" });
const date = (name, label = name) => ({ name, label, type: "datetime-local" });
const json = (name, label = name, fallback = {}) => ({ name, label, type: "json", fallback });

export const modules = [
  { key: "roles", title: "Roles", description: "Perfiles y permisos del sistema.", columns: ["nombre", "descripcion", "permisos"], fields: [text("nombre", "Nombre", true), text("descripcion", "Descripcion"), json("permisos", "Permisos", [])], empty: { nombre: "", descripcion: "", permisos: [] } },
  { key: "usuarios", title: "Usuarios", description: "Accesos del equipo Translogix.", columns: ["nombre", "email", "telefono", "activo", "rol_id"], fields: [text("nombre", "Nombre", true), text("email", "Email", true), text("password_hash", "Password hash", true), id("rol_id"), bool("activo", "Activo"), text("telefono", "Telefono")], empty: { nombre: "", email: "", password_hash: "", rol_id: "", activo: true, telefono: "" } },
  { key: "conductores", title: "Conductores", description: "Personal encargado de realizar entregas.", columns: ["nombre_completo", "dni", "licencia_conducir", "categoria_licencia", "telefono", "estado"], fields: [id("usuario_id"), text("nombre_completo", "Nombre completo", true), text("dni", "DNI", true), text("licencia_conducir", "Licencia"), text("categoria_licencia", "Categoria"), text("telefono", "Telefono"), text("estado", "Estado")], empty: { usuario_id: "", nombre_completo: "", dni: "", licencia_conducir: "", categoria_licencia: "A-IIb", telefono: "", estado: "disponible" } },
  { key: "vehiculos", title: "Vehiculos", description: "Control operativo de unidades de transporte.", columns: ["placa", "marca", "modelo", "anio", "tipo", "estado", "kilometraje"], fields: [text("placa", "Placa", true), text("marca", "Marca"), text("modelo", "Modelo"), num("anio", "Anio"), text("tipo", "Tipo"), num("capacidad_kg", "Capacidad kg"), num("capacidad_m3", "Capacidad m3"), text("estado", "Estado"), num("kilometraje", "Kilometraje")], empty: { placa: "", marca: "", modelo: "", anio: new Date().getFullYear(), tipo: "furgoneta", capacidad_kg: 1000, capacidad_m3: 6, estado: "operativo", kilometraje: 0 } },
  { key: "clientes", title: "Clientes", description: "Empresas y contactos de entrega.", columns: ["razon_social", "ruc", "contacto", "telefono", "email", "activo"], fields: [text("razon_social", "Razon social", true), text("ruc", "RUC", true), text("contacto", "Contacto"), text("telefono", "Telefono"), text("email", "Email"), bool("activo", "Activo"), json("direccion", "Direccion")], empty: { razon_social: "", ruc: "", contacto: "", telefono: "", email: "", activo: true, direccion: { calle: "", distrito: "", ciudad: "Lima", coordenadas: { lat: -12.0464, lng: -77.0428 } } } },
  { key: "zonas", title: "Zonas", description: "Zonas geograficas de operacion.", columns: ["nombre", "distritos", "activa"], fields: [text("nombre", "Nombre", true), json("distritos", "Distritos", []), bool("activa", "Activa")], empty: { nombre: "", distritos: [], activa: true } },
  { key: "rutas", title: "Rutas", description: "Rutas y puntos de parada.", columns: ["nombre", "zona_id", "distancia_km", "tiempo_estimado_min", "activa"], fields: [text("nombre", "Nombre", true), id("zona_id"), json("puntos_parada", "Puntos de parada", []), num("distancia_km", "Distancia km"), num("tiempo_estimado_min", "Tiempo min"), bool("activa", "Activa")], empty: { nombre: "", zona_id: "", puntos_parada: [], distancia_km: 0, tiempo_estimado_min: 0, activa: true } },
  { key: "pedidos", title: "Pedidos", description: "Cargas solicitadas por clientes.", columns: ["codigo", "descripcion", "peso_kg", "volumen_m3", "estado", "prioridad"], fields: [text("codigo", "Codigo", true), id("cliente_id"), text("descripcion", "Descripcion"), num("peso_kg", "Peso kg"), num("volumen_m3", "Volumen m3"), json("direccion_entrega", "Direccion entrega"), date("fecha_solicitud", "Fecha solicitud"), date("fecha_entrega_estimada", "Entrega estimada"), text("estado", "Estado"), text("prioridad", "Prioridad"), text("observaciones", "Observaciones")], empty: { codigo: "", cliente_id: "", descripcion: "", peso_kg: 0, volumen_m3: 0, direccion_entrega: { calle: "", distrito: "", coordenadas: { lat: -12.0464, lng: -77.0428 } }, fecha_solicitud: "", fecha_entrega_estimada: "", estado: "pendiente", prioridad: "normal", observaciones: "" } },
  { key: "despachos", title: "Despachos", description: "Asignacion de rutas, vehiculos y conductores.", columns: ["codigo", "estado", "fecha_salida", "fecha_llegada_estimada"], fields: [text("codigo", "Codigo", true), id("ruta_id"), id("vehiculo_id"), id("conductor_id"), json("pedidos_ids", "Pedidos IDs", []), id("operador_id"), date("fecha_salida", "Fecha salida"), date("fecha_llegada_estimada", "Llegada estimada"), date("fecha_llegada_real", "Llegada real"), text("estado", "Estado")], empty: { codigo: "", ruta_id: "", vehiculo_id: "", conductor_id: "", pedidos_ids: [], operador_id: "", fecha_salida: "", fecha_llegada_estimada: "", fecha_llegada_real: "", estado: "programado" } },
  { key: "seguimiento_gps", title: "Seguimiento GPS", description: "Ubicacion y velocidad de vehiculos.", columns: ["despacho_id", "vehiculo_id", "velocidad_kmh", "timestamp"], fields: [id("despacho_id"), id("vehiculo_id"), json("coordenadas", "Coordenadas"), num("velocidad_kmh", "Velocidad km/h"), date("timestamp", "Timestamp")], empty: { despacho_id: "", vehiculo_id: "", coordenadas: { lat: -12.0464, lng: -77.0428 }, velocidad_kmh: 0, timestamp: "" } },
  { key: "incidencias", title: "Incidencias", description: "Eventos reportados durante operacion.", columns: ["tipo", "descripcion", "estado", "fecha_reporte"], fields: [id("despacho_id"), text("tipo", "Tipo"), text("descripcion", "Descripcion"), json("coordenadas", "Coordenadas"), id("reportado_por"), text("estado", "Estado"), date("fecha_reporte", "Fecha reporte"), date("fecha_resolucion", "Fecha resolucion")], empty: { despacho_id: "", tipo: "", descripcion: "", coordenadas: { lat: -12.0464, lng: -77.0428 }, reportado_por: "", estado: "abierto", fecha_reporte: "", fecha_resolucion: "" } },
  { key: "mantenimientos", title: "Mantenimientos", description: "Historial de mantenimiento vehicular.", columns: ["vehiculo_id", "tipo", "costo_soles", "taller", "fecha_entrada"], fields: [id("vehiculo_id"), text("tipo", "Tipo"), text("descripcion", "Descripcion"), num("costo_soles", "Costo soles"), text("taller", "Taller"), date("fecha_entrada", "Fecha entrada"), date("fecha_salida", "Fecha salida"), num("km_al_mantenimiento", "Km mantenimiento"), num("proximo_mantenimiento_km", "Proximo km")], empty: { vehiculo_id: "", tipo: "preventivo", descripcion: "", costo_soles: 0, taller: "", fecha_entrada: "", fecha_salida: "", km_al_mantenimiento: 0, proximo_mantenimiento_km: 0 } },
  { key: "reportes", title: "Reportes", description: "Resumenes operativos.", columns: ["tipo", "fecha", "generado_por", "resumen"], fields: [text("tipo", "Tipo"), date("fecha", "Fecha"), id("generado_por"), json("resumen", "Resumen")], empty: { tipo: "diario", fecha: "", generado_por: "", resumen: {} } },
  { key: "notificaciones", title: "Notificaciones", description: "Alertas para usuarios.", columns: ["usuario_id", "tipo", "mensaje", "leida"], fields: [id("usuario_id"), text("tipo", "Tipo"), text("mensaje", "Mensaje"), id("referencia_id"), text("referencia_tipo", "Referencia tipo"), bool("leida", "Leida")], empty: { usuario_id: "", tipo: "", mensaje: "", referencia_id: "", referencia_tipo: "", leida: false } },
  { key: "publicaciones_feed", title: "Feed", description: "Publicaciones internas con multimedia.", columns: ["autor_id", "tipo_publicacion", "contenido", "estado"], fields: [id("autor_id"), id("referencia_despacho"), text("tipo_publicacion", "Tipo"), text("contenido", "Contenido"), json("multimedia", "Multimedia", []), json("reacciones", "Reacciones", []), text("estado", "Estado")], empty: { autor_id: "", referencia_despacho: "", tipo_publicacion: "general", contenido: "", multimedia: [], reacciones: [], estado: "publicado" } },
  { key: "comentarios", title: "Comentarios", description: "Comentarios del feed corporativo.", columns: ["publicacion_id", "autor_id", "texto"], fields: [id("publicacion_id"), id("autor_id"), text("texto", "Texto")], empty: { publicacion_id: "", autor_id: "", texto: "" } },
  { key: "suscripciones", title: "Suscripciones", description: "Planes Plus y Premium seleccionados por usuarios.", columns: ["usuario_id", "plan", "estado", "fecha_inicio", "caracteristicas"], fields: [id("usuario_id"), text("plan", "Plan plus/premium", true), text("estado", "Estado"), date("fecha_inicio", "Fecha inicio"), date("fecha_fin", "Fecha fin"), json("caracteristicas", "Caracteristicas", [])], empty: { usuario_id: "", plan: "plus", estado: "activa", fecha_inicio: "", fecha_fin: "", caracteristicas: ["CRUD logistico"] } },
];
