export const modules = [
  {
    key: "clientes",
    title: "Clientes",
    description: "Gestion de empresas y contactos de entrega.",
    columns: ["razon_social", "ruc", "contacto", "telefono", "email", "activo"],
    fields: [
      { name: "razon_social", label: "Razon social", required: true },
      { name: "ruc", label: "RUC", required: true },
      { name: "contacto", label: "Contacto" },
      { name: "telefono", label: "Telefono" },
      { name: "email", label: "Email", type: "email" },
      { name: "activo", label: "Activo", type: "checkbox" },
      { name: "direccion", label: "Direccion", type: "json" },
    ],
    empty: {
      razon_social: "",
      ruc: "",
      contacto: "",
      telefono: "",
      email: "",
      activo: true,
      direccion: {
        calle: "",
        distrito: "",
        ciudad: "Lima",
        coordenadas: { lat: -12.0464, lng: -77.0428 },
      },
    },
  },
  {
    key: "vehiculos",
    title: "Vehiculos",
    description: "Control operativo de unidades de transporte.",
    columns: ["placa", "marca", "modelo", "anio", "tipo", "estado", "kilometraje"],
    fields: [
      { name: "placa", label: "Placa", required: true },
      { name: "marca", label: "Marca" },
      { name: "modelo", label: "Modelo" },
      { name: "anio", label: "Anio", type: "number" },
      { name: "tipo", label: "Tipo" },
      { name: "capacidad_kg", label: "Capacidad kg", type: "number" },
      { name: "capacidad_m3", label: "Capacidad m3", type: "number" },
      { name: "estado", label: "Estado" },
      { name: "kilometraje", label: "Kilometraje", type: "number" },
    ],
    empty: {
      placa: "",
      marca: "",
      modelo: "",
      anio: new Date().getFullYear(),
      tipo: "furgoneta",
      capacidad_kg: 1000,
      capacidad_m3: 6,
      estado: "operativo",
      kilometraje: 0,
    },
  },
  {
    key: "pedidos",
    title: "Pedidos",
    description: "Seguimiento de cargas solicitadas por clientes.",
    columns: ["codigo", "descripcion", "peso_kg", "volumen_m3", "estado", "prioridad"],
    fields: [
      { name: "codigo", label: "Codigo", required: true },
      { name: "cliente_id", label: "Cliente ID" },
      { name: "descripcion", label: "Descripcion" },
      { name: "peso_kg", label: "Peso kg", type: "number" },
      { name: "volumen_m3", label: "Volumen m3", type: "number" },
      { name: "estado", label: "Estado" },
      { name: "prioridad", label: "Prioridad" },
      { name: "observaciones", label: "Observaciones" },
      { name: "direccion_entrega", label: "Direccion entrega", type: "json" },
    ],
    empty: {
      codigo: "",
      cliente_id: "",
      descripcion: "",
      peso_kg: 0,
      volumen_m3: 0,
      estado: "pendiente",
      prioridad: "normal",
      observaciones: "",
      direccion_entrega: {
        calle: "",
        distrito: "",
        coordenadas: { lat: -12.0464, lng: -77.0428 },
      },
    },
  },
  {
    key: "despachos",
    title: "Despachos",
    description: "Asignacion de rutas, vehiculos y conductores.",
    columns: ["codigo", "estado", "fecha_salida", "fecha_llegada_estimada"],
    fields: [
      { name: "codigo", label: "Codigo", required: true },
      { name: "ruta_id", label: "Ruta ID" },
      { name: "vehiculo_id", label: "Vehiculo ID" },
      { name: "conductor_id", label: "Conductor ID" },
      { name: "operador_id", label: "Operador ID" },
      { name: "pedidos_ids", label: "Pedidos IDs", type: "json" },
      { name: "fecha_salida", label: "Fecha salida", type: "datetime-local" },
      { name: "fecha_llegada_estimada", label: "Llegada estimada", type: "datetime-local" },
      { name: "estado", label: "Estado" },
    ],
    empty: {
      codigo: "",
      ruta_id: "",
      vehiculo_id: "",
      conductor_id: "",
      operador_id: "",
      pedidos_ids: [],
      fecha_salida: "",
      fecha_llegada_estimada: "",
      estado: "programado",
    },
  },
  {
    key: "conductores",
    title: "Conductores",
    description: "Personal encargado de realizar entregas.",
    columns: ["nombre_completo", "dni", "licencia_conducir", "categoria_licencia", "telefono", "estado"],
    fields: [
      { name: "nombre_completo", label: "Nombre completo", required: true },
      { name: "dni", label: "DNI", required: true },
      { name: "licencia_conducir", label: "Licencia" },
      { name: "categoria_licencia", label: "Categoria" },
      { name: "telefono", label: "Telefono" },
      { name: "estado", label: "Estado" },
    ],
    empty: {
      nombre_completo: "",
      dni: "",
      licencia_conducir: "",
      categoria_licencia: "A-IIb",
      telefono: "",
      estado: "disponible",
    },
  },
];
