const text = (name, label = name, required = false) => ({ name, label, required });
const num = (name, label = name) => ({ name, label, type: "number" });
const bool = (name, label = name) => ({ name, label, type: "checkbox" });
const date = (name, label = name) => ({ name, label, type: "datetime-local" });
const json = (name, label = name, fallback = {}) => ({ name, label, type: "json", fallback });

export const modules = [
  { key: "roles", title: "Roles", description: "Perfiles y permisos del sistema.", columns: ["nombre", "descripcion", "permisos"], fields: [text("nombre", "Nombre", true), text("descripcion", "Descripcion"), json("permisos", "Permisos", [])], empty: { nombre: "", descripcion: "", permisos: [] } },
  { key: "usuarios", title: "Usuarios", description: "Accesos del equipo Translogix.", columns: ["nombre", "email", "telefono", "activo"], fields: [text("nombre", "Nombre", true), text("email", "Email", true), text("telefono", "Telefono"), bool("activo", "Activo")], empty: { nombre: "", email: "", telefono: "", activo: true } },
  { key: "conductores", title: "Conductores", description: "Personal encargado de realizar entregas.", columns: ["nombre_completo", "dni", "licencia_conducir", "categoria_licencia", "telefono", "estado"], fields: [text("nombre_completo", "Nombre completo", true), text("dni", "DNI", true), text("licencia_conducir", "Licencia"), text("categoria_licencia", "Categoria"), text("telefono", "Telefono"), text("estado", "Estado")], empty: { nombre_completo: "", dni: "", licencia_conducir: "", categoria_licencia: "A-IIb", telefono: "", estado: "disponible" } },
  { key: "vehiculos", title: "Vehiculos", description: "Control operativo de unidades de transporte.", columns: ["placa", "marca", "modelo", "anio", "tipo", "estado", "kilometraje"], fields: [text("placa", "Placa", true), text("marca", "Marca"), text("modelo", "Modelo"), num("anio", "Anio"), text("tipo", "Tipo"), num("capacidad_kg", "Capacidad kg"), num("capacidad_m3", "Capacidad m3"), text("estado", "Estado"), num("kilometraje", "Kilometraje")], empty: { placa: "", marca: "", modelo: "", anio: new Date().getFullYear(), tipo: "furgoneta", capacidad_kg: 1000, capacidad_m3: 6, estado: "operativo", kilometraje: 0 } },
  { key: "clientes", title: "Clientes", description: "Empresas y contactos de entrega.", columns: ["razon_social", "ruc", "contacto", "telefono", "email", "activo"], fields: [text("razon_social", "Razon social", true), text("ruc", "RUC", true), text("contacto", "Contacto"), text("telefono", "Telefono"), text("email", "Email"), bool("activo", "Activo"), json("direccion", "Direccion")], empty: { razon_social: "", ruc: "", contacto: "", telefono: "", email: "", activo: true, direccion: { calle: "", distrito: "", ciudad: "Lima", coordenadas: { lat: -12.0464, lng: -77.0428 } } } },
  { key: "zonas", title: "Zonas", description: "Zonas geograficas de operacion.", columns: ["nombre", "distritos", "activa"], fields: [text("nombre", "Nombre", true), json("distritos", "Distritos", []), bool("activa", "Activa")], empty: { nombre: "", distritos: [], activa: true } },
  { key: "rutas", title: "Rutas", description: "Rutas y puntos de parada.", columns: ["nombre", "distancia_km", "tiempo_estimado_min", "activa"], fields: [text("nombre", "Nombre", true), json("puntos_parada", "Puntos de parada", []), num("distancia_km", "Distancia km"), num("tiempo_estimado_min", "Tiempo min"), bool("activa", "Activa")], empty: { nombre: "", puntos_parada: [], distancia_km: 0, tiempo_estimado_min: 0, activa: true } },
  { key: "pedidos", title: "Pedidos", description: "Cargas solicitadas por clientes.", columns: ["codigo", "descripcion", "peso_kg", "volumen_m3", "estado", "prioridad"], fields: [text("codigo", "Codigo", true), text("descripcion", "Descripcion"), num("peso_kg", "Peso kg"), num("volumen_m3", "Volumen m3"), json("direccion_entrega", "Direccion entrega"), date("fecha_solicitud", "Fecha solicitud"), date("fecha_entrega_estimada", "Entrega estimada"), text("estado", "Estado"), text("prioridad", "Prioridad"), text("observaciones", "Observaciones")], empty: { codigo: "", descripcion: "", peso_kg: 0, volumen_m3: 0, direccion_entrega: { calle: "", distrito: "", coordenadas: { lat: -12.0464, lng: -77.0428 } }, fecha_solicitud: "", fecha_entrega_estimada: "", estado: "pendiente", prioridad: "normal", observaciones: "" } },
  { key: "despachos", title: "Despachos", description: "Asignacion de rutas, vehiculos y conductores.", columns: ["codigo", "estado", "fecha_salida", "fecha_llegada_estimada"], fields: [text("codigo", "Codigo", true), date("fecha_salida", "Fecha salida"), date("fecha_llegada_estimada", "Llegada estimada"), date("fecha_llegada_real", "Llegada real"), text("estado", "Estado")], empty: { codigo: "", fecha_salida: "", fecha_llegada_estimada: "", fecha_llegada_real: "", estado: "programado" } },
  { key: "seguimiento_gps", title: "Seguimiento GPS", description: "Ubicacion y velocidad de vehiculos.", columns: ["coordenadas", "velocidad_kmh", "timestamp"], fields: [json("coordenadas", "Coordenadas"), num("velocidad_kmh", "Velocidad km/h"), date("timestamp", "Timestamp")], empty: { coordenadas: { lat: -12.0464, lng: -77.0428 }, velocidad_kmh: 0, timestamp: "" } },
  { key: "incidencias", title: "Incidencias", description: "Eventos reportados durante operacion.", columns: ["tipo", "descripcion", "estado", "fecha_reporte"], fields: [text("tipo", "Tipo"), text("descripcion", "Descripcion"), json("coordenadas", "Coordenadas"), text("estado", "Estado"), date("fecha_reporte", "Fecha reporte"), date("fecha_resolucion", "Fecha resolucion")], empty: { tipo: "", descripcion: "", coordenadas: { lat: -12.0464, lng: -77.0428 }, estado: "abierto", fecha_reporte: "", fecha_resolucion: "" } },
  { key: "mantenimientos", title: "Mantenimientos", description: "Historial de mantenimiento vehicular.", columns: ["tipo", "costo_soles", "taller", "fecha_entrada"], fields: [text("tipo", "Tipo"), text("descripcion", "Descripcion"), num("costo_soles", "Costo soles"), text("taller", "Taller"), date("fecha_entrada", "Fecha entrada"), date("fecha_salida", "Fecha salida"), num("km_al_mantenimiento", "Km mantenimiento"), num("proximo_mantenimiento_km", "Proximo km")], empty: { tipo: "preventivo", descripcion: "", costo_soles: 0, taller: "", fecha_entrada: "", fecha_salida: "", km_al_mantenimiento: 0, proximo_mantenimiento_km: 0 } },
  { key: "reportes", title: "Reportes", description: "Resumenes operativos.", columns: ["tipo", "fecha", "resumen"], fields: [text("tipo", "Tipo"), date("fecha", "Fecha"), json("resumen", "Resumen")], empty: { tipo: "diario", fecha: "", resumen: {} } },
  { key: "notificaciones", title: "Notificaciones", description: "Alertas para usuarios.", columns: ["tipo", "mensaje", "referencia_tipo", "leida"], fields: [text("tipo", "Tipo"), text("mensaje", "Mensaje"), text("referencia_tipo", "Referencia tipo"), bool("leida", "Leida")], empty: { tipo: "", mensaje: "", referencia_tipo: "", leida: false } },
  { key: "publicaciones_feed", title: "Feed", description: "Publicaciones internas con multimedia.", columns: ["tipo_publicacion", "contenido", "estado"], fields: [text("tipo_publicacion", "Tipo"), text("contenido", "Contenido"), json("multimedia", "Multimedia", []), text("estado", "Estado")], empty: { tipo_publicacion: "general", contenido: "", multimedia: [], estado: "publicado" } },
  { key: "comentarios", title: "Comentarios", description: "Comentarios del feed corporativo con reacciones.", columns: ["texto"], fields: [text("texto", "Texto")], empty: { texto: "" } },
  { key: "suscripciones", title: "Suscripciones", description: "Planes Plus y Premium seleccionados por usuarios.", columns: ["plan", "estado", "fecha_inicio", "caracteristicas"], fields: [text("plan", "Plan plus/premium", true), text("estado", "Estado"), date("fecha_inicio", "Fecha inicio"), date("fecha_fin", "Fecha fin"), json("caracteristicas", "Caracteristicas", [])], empty: { plan: "plus", estado: "activa", fecha_inicio: "", fecha_fin: "", caracteristicas: ["CRUD logistico"] } },
];
